version: "3.0"
services:
    web:
        build: ./web
        ports: 
            - "8080:3000"
        expose:
            - 3000
        volumes:
            - "./web/src:/app/src"
        restart: unless-stopped
        networks:
            - default
    
    proxy:
        build: ./nginx
        restart: unless-stopped
        ports:
            - "3000:80"
        
    db:
        image: mongo
        restart: unless-stopped
        expose:
            - 27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

volumes:
    proxy: