version: "3.0"
services:
    web:
        build: ./web
        ports: 
            - "8080:3000"
        volumes:
            - "./web/src:/app/src"
        restart: unless-stopped
        networks:
            - default

volumes:
    proxy:
        